// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEFu47QMsNBXTTCN6Tv6CXLYkA8HqaOQk',
    appId: '1:720388038129:web:d5f0029f375e2ffb8db850',
    messagingSenderId: '720388038129',
    projectId: 'car-booking-478c3',
    authDomain: 'car-booking-478c3.firebaseapp.com',
    storageBucket: 'car-booking-478c3.appspot.com',
    measurementId: 'G-RFPY7LYMV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwAFLyL9OTFg_341FFV-J4nCk-FMe1XeE',
    appId: '1:720388038129:android:aca74a4e55c7f44a8db850',
    messagingSenderId: '720388038129',
    projectId: 'car-booking-478c3',
    storageBucket: 'car-booking-478c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMDE1JF2YoXU21IEwT1D-YtwOrXHs2diM',
    appId: '1:720388038129:ios:446956cfc3f168e58db850',
    messagingSenderId: '720388038129',
    projectId: 'car-booking-478c3',
    storageBucket: 'car-booking-478c3.appspot.com',
    iosBundleId: 'com.example.cabBookingUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMDE1JF2YoXU21IEwT1D-YtwOrXHs2diM',
    appId: '1:720388038129:ios:8d6b7801394fac548db850',
    messagingSenderId: '720388038129',
    projectId: 'car-booking-478c3',
    storageBucket: 'car-booking-478c3.appspot.com',
    iosBundleId: 'com.example.cabBookingUser.RunnerTests',
  );
}
